url: https://blackstoneengineering.github.io
baseurl: /shainarutherford.com/
header-bg-image: header-bg-2-grey.jpg

# Site settings
title: Shaina Rutherford
email: your-email@domain.com
description: "General contractor with a specialty in bathroom / kitchen remodels and custom tile work. Flooring, framing, roofing, trim work, doors, windows, siding and much more are our specialty."


# Team names, titles and social links
people:
- name: Shaina Rutherford
  pic: 1
  position: Head Builder
  social:
    - title: instagram
      url: #
    - title: facebook
      url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/

# Postal address (add as many lines as necessary)
address:
  - line: Line 1
  - line: Line 2

# Build settings
markdown: kramdown
permalink: pretty